server:
  port: 8081

spring:
  application:
    name: stoke
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: 123.qwe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        type:
          descriptor:
            sql:
              BasicBinder:
                log: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
security:
  user:
    name: admin
    password: admin
  jwt:
    secret-key: 1d98081c2dbe6d942d586219d27be0b461e04e9b21629e15ab17942be81467a5
    expiration-time: 3600000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    disable-swagger-default-url: true
    use-root-path: true

# Configuração do diretório de uploads
app:
  file-storage-location: uploads
  max-file-size: 10MB
  max-request-size: 10MB
